import {
  COMPLEXITY_PAGE_LIMITS,
  COMPLEXITY_SLOWDOWN,
  PAGES_PER_HOUR,
} from './constants';
import type { Book, CatalogBook } from './types';

export const complexityOf = (pages: number) =>
  COMPLEXITY_PAGE_LIMITS.filter((limit) => pages >= limit).length + 1;

export const hoursToRead = (pages: number) =>
  Math.ceil(
    (pages / PAGES_PER_HOUR) *
      (1 + (complexityOf(pages) - 1) * COMPLEXITY_SLOWDOWN),
  );

const BOOK_LIST: Book[] = [
  {
    id: 'animal-farm',
    title: 'Animal Farm',
    author: 'George Orwell',
    theme: 'Satire',
    pages: 112,
  },
  {
    id: 'little-prince',
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    theme: 'Fable',
    pages: 96,
  },
  {
    id: 'stranger',
    title: 'The Stranger',
    author: 'Albert Camus',
    theme: 'Philosophy',
    pages: 123,
  },
  {
    id: 'old-man-sea',
    title: 'The Old Man and the Sea',
    author: 'Ernest Hemingway',
    theme: 'Adventure',
    pages: 127,
  },
  {
    id: 'metamorphosis',
    title: 'The Metamorphosis',
    author: 'Franz Kafka',
    theme: 'Absurd',
    pages: 96,
  },
  {
    id: 'of-mice-men',
    title: 'Of Mice and Men',
    author: 'John Steinbeck',
    theme: 'Drama',
    pages: 107,
  },
  {
    id: 'jekyll-hyde',
    title: 'Strange Case of Dr Jekyll and Mr Hyde',
    author: 'Robert Louis Stevenson',
    theme: 'Horror',
    pages: 96,
  },
  {
    id: 'christmas-carol',
    title: 'A Christmas Carol',
    author: 'Charles Dickens',
    theme: 'Fable',
    pages: 104,
  },
  {
    id: 'candide',
    title: 'Candide',
    author: 'Voltaire',
    theme: 'Satire',
    pages: 144,
  },
  {
    id: 'great-gatsby',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    theme: 'Drama',
    pages: 180,
  },
  {
    id: 'alchemist',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    theme: 'Adventure',
    pages: 190,
  },
  {
    id: 'catcher-rye',
    title: 'The Catcher in the Rye',
    author: 'J. D. Salinger',
    theme: 'Coming of age',
    pages: 234,
  },
  {
    id: 'hobbit',
    title: 'The Hobbit',
    author: 'J. R. R. Tolkien',
    theme: 'Fantasy',
    pages: 310,
  },
  {
    id: '1984',
    title: '1984',
    author: 'George Orwell',
    theme: 'Dystopia',
    pages: 328,
  },
  {
    id: 'brave-new-world',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    theme: 'Dystopia',
    pages: 311,
  },
  {
    id: 'fahrenheit-451',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    theme: 'Dystopia',
    pages: 249,
  },
  {
    id: 'dune',
    title: 'Dune',
    author: 'Frank Herbert',
    theme: 'Science fiction',
    pages: 612,
  },
  {
    id: 'foundation',
    title: 'Foundation',
    author: 'Isaac Asimov',
    theme: 'Science fiction',
    pages: 255,
  },
  {
    id: 'neuromancer',
    title: 'Neuromancer',
    author: 'William Gibson',
    theme: 'Science fiction',
    pages: 271,
  },
  {
    id: 'frankenstein',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    theme: 'Horror',
    pages: 280,
  },
  {
    id: 'dracula',
    title: 'Dracula',
    author: 'Bram Stoker',
    theme: 'Horror',
    pages: 418,
  },
  {
    id: 'pride-prejudice',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    theme: 'Romance',
    pages: 432,
  },
  {
    id: 'jane-eyre',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    theme: 'Romance',
    pages: 532,
  },
  {
    id: 'wuthering-heights',
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    theme: 'Romance',
    pages: 416,
  },
  {
    id: 'murder-orient-express',
    title: 'Murder on the Orient Express',
    author: 'Agatha Christie',
    theme: 'Crime',
    pages: 256,
  },
  {
    id: 'hound-baskervilles',
    title: 'The Hound of the Baskervilles',
    author: 'Arthur Conan Doyle',
    theme: 'Crime',
    pages: 256,
  },
  {
    id: 'name-of-the-rose',
    title: 'The Name of the Rose',
    author: 'Umberto Eco',
    theme: 'Crime',
    pages: 536,
  },
  {
    id: 'crime-punishment',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    theme: 'Philosophy',
    pages: 545,
  },
  {
    id: 'brothers-karamazov',
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    theme: 'Philosophy',
    pages: 824,
  },
  {
    id: 'sophies-world',
    title: "Sophie's World",
    author: 'Jostein Gaarder',
    theme: 'Philosophy',
    pages: 544,
  },
  {
    id: 'three-musketeers',
    title: 'The Three Musketeers',
    author: 'Alexandre Dumas',
    theme: 'Adventure',
    pages: 700,
  },
  {
    id: 'count-monte-cristo',
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    theme: 'Adventure',
    pages: 1276,
  },
  {
    id: 'moby-dick',
    title: 'Moby-Dick',
    author: 'Herman Melville',
    theme: 'Adventure',
    pages: 635,
  },
  {
    id: 'les-miserables',
    title: 'Les Misérables',
    author: 'Victor Hugo',
    theme: 'Historical',
    pages: 1488,
  },
  {
    id: 'war-and-peace',
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    theme: 'Historical',
    pages: 1225,
  },
  {
    id: 'anna-karenina',
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    theme: 'Romance',
    pages: 864,
  },
  {
    id: 'don-quixote',
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    theme: 'Satire',
    pages: 1056,
  },
  {
    id: 'ulysses',
    title: 'Ulysses',
    author: 'James Joyce',
    theme: 'Modernism',
    pages: 730,
  },
  {
    id: 'lord-of-the-rings',
    title: 'The Lord of the Rings',
    author: 'J. R. R. Tolkien',
    theme: 'Fantasy',
    pages: 1178,
  },
  {
    id: 'sapiens',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    theme: 'History',
    pages: 443,
  },
  {
    id: 'brief-history-time',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    theme: 'Science',
    pages: 212,
  },
  {
    id: 'selfish-gene',
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    theme: 'Science',
    pages: 360,
  },
  {
    id: 'art-of-war',
    title: 'The Art of War',
    author: 'Sun Tzu',
    theme: 'Strategy',
    pages: 160,
  },
  {
    id: 'the-prince',
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    theme: 'Politics',
    pages: 140,
  },
  {
    id: 'meditations',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    theme: 'Philosophy',
    pages: 254,
  },
];

export const BOOKS: readonly CatalogBook[] = BOOK_LIST.map((book) => ({
  ...book,
  complexity: complexityOf(book.pages),
  hours: hoursToRead(book.pages),
}));

export const getBook = (id: string | undefined) =>
  BOOKS.find((book) => book.id === id);
